#!/bin/sh

if grep -q drop-rotate /var/spool/cron/root; then
    echo "cron exist"
else
  echo "* * * * * /opt/drop-core/scripts/drop-rotate >/dev/null 2>&1" >> /var/spool/cron/root
  echo "cron ok"
fi

cp /opt/drop-core/conf/drop-core.service /etc/systemd/system/ && systemctl daemon-reload
systemctl enable drop-core

## create symlink
rm -f /usr/bin/drop-core
ln -s /opt/drop-core/scripts/drop-core /usr/bin/drop-core

## start service
systemctl restart drop-core
