#!/bin/bash
#
# Rotate drop's fuctions logs 
#


cd /var/lib/drop/logs

rm -f *.log.1
find . -iname "*.log" -exec cp "{}" "{}.1" \;
find . -iname "*.log" -exec /bin/sh -c "> '{}'" ';'

# check started dependant..
/opt/drop-core/scripts/drop-core stop_s
